title: General nerdness
description: >- # this means to ignore newlines until "baseurl:"
  Trying to blag is never easy, that's why I have no posts xD
url: "https://Darkade.github.io"
twitter_username: darkade
github_username:  darkade

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
