title: General nerdness
author: Ivan Reyes
tagline: Trying to blag is never easy, that's why I have no posts xD
description: >-
  Hola! Soy Ivan Reyes, este es mi blog personal. Escribo de programación,
  juegos de mesa y juegos de rol. O sea, mi general nerdness.

url: https://ivan.reyescon.de
remote_theme: Darkade/Darkade.github.io-theme
lang: es_MX

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

paginate: 5

twitter_username: darkade
github_username:  darkade
linkedin_username: ivanreyesce

analytics: UA-144585764-1

social:
  name: Ivan Reyes
  links:
    - https://twitter.com/darkade
    - https://www.linkedin.com/in/ivanreyesce
    - https://github.com/darkade
