title: General nerdness
author: Anya Reyes
tagline: Maths, RPGs, Boardgames & Coding.
description: >-
  HI! I'm Anya Reyes, also known as Darkade this is my blog.
  I writte about programming, board games and TTRPGs.
  That's to say, my general nerdness.

url: https://darkade.quest
theme: darkade.github.io-theme
lang: es_MX
showlogo: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      locale: es_MX

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jemoji
  - jekyll-target-blank

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  sort_reverse: true
  trail:
    before: 2
    after: 2

giscus:
  repo: "Darkade/Darkade.github.io-comments"
  repoid: "R_kgDOIuNbEA"
  category: "Announcements"
  categoryid: "DIC_kwDOIuNbEM4CTaKd"
  mapping: "pathname"

markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge

excerpt_separator: <!--more-->

github_username:  darkade

twitter:
  username: darkade
  card: summary_large_image

mastodon:
  server: dice.camp
  user: "@darkade"

analytics: UA-144585764-1

social:
  name: Anya Reyes
  links:
    - https://twitter.com/darkade
    - https://github.com/darkade
