title: General nerdness
author: Ivan Reyes
tagline: Trying to blag is never easy, that's why I have no posts xD
description: >-
  :3

remote_theme: Darkade/Darkade.github.io-theme

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

paginate: 5

twitter_username: darkade
github_username:  darkade
linkedin_username: ivanreyesce

social:
  name: Ivan Reyes
  links:
    - https://twitter.com/darkade
    - https://www.linkedin.com/in/ivanreyesce
    - https://github.com/darkade
