title: General nerdness
author: I Reyes
tagline: Trying to blag is getting easier. So, here are some posts.
description: >-
  Hola! Soy I Reyes, este es mi blog personal. Escribo de programación,
  juegos de mesa y juegos de rol. O sea, mi general nerdness.

url: https://i.reyescon.de
theme: darkade.github.io-theme
lang: es_MX

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jemoji
  - jekyll-target-blank

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  sort_reverse: true

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

twitter_username: darkade
github_username:  darkade
linkedin_username: ivanreyesce

analytics: UA-144585764-1

social:
  name: Ivan Reyes
  links:
    - https://twitter.com/darkade
    - https://www.linkedin.com/in/ivanreyesce
    - https://github.com/darkade
